### ISSUE TITLE
Needles not move

### ISSUE THREAD

**Issue by psy501** [FdeAlexa/PeppyMeter_and_moOde#8] opened 2024-12-08 09:09 UTC
Hello,

Thanks for this addon, but I can't get the needles to move, although I think I've installed it correctly. What is the purpose of the aplay -l command? Is it necessary to use the information somewhere?  

T
![Capture d'écran 2024-12-08 095716](https://github.com/user-attachments/assets/797600b5-ce27-416e-ab58-835972f37a95)
![Capture d'écran 2024-12-08 095812](https://github.com/user-attachments/assets/84432b36-1a05-48b9-a75f-b64b34182b8a)
hanks

**Comment by FdeAlexa** [comment] 2024-12-08 10:57
Hello psy501,
would you please:
1. send: the content of _sndloop.conf ( cat /etc/alsa/conf.d/_sndaloop.conf )
2. list: the content of your /var/tmp ( ls -lia /var/tmp/p* )
3. tell us: which default user are you using (pi or what)
Best regards,
Francesco

**Comment by psy501** [comment] 2024-12-08 17:39
I have rename my default user as : alexis (it is super user) I use dir home/alexis/ for the install

Thanks 
Alexis

![Capture d'écran 2024-12-08 183926](https://github.com/user-attachments/assets/98d7cbe4-339d-4864-bf26-46913d7ec8dc)
![Capture d'écran 2024-12-08 184036](https://github.com/user-attachments/assets/33b76a7e-346d-4688-8865-986457030dae)

**Comment by FdeAlexa** [comment] 2024-12-08 18:25
Hello psy501,
it looks like you have skipped the modification of moOde step in particular the link [moOde 7.2.0and later](https://github.com/FdeAlexa/PeppyMeter_and_moOde/blob/main/2_4_moOde720.md).
Please try it and verify back  the content of _sndloop.conf.
Best regards,
Francesco

**Comment by psy501** [comment] 2024-12-08 18:57
Ok thanks, I did not make this modification because I am under moode audio 9.1.5 2024-11-26. 

![Capture d'écran 2024-12-08 195313](https://github.com/user-attachments/assets/12754ba8-357f-4b73-bd58-a506dd600f8b)
![Capture d'écran 2024-12-08 195849](https://github.com/user-attachments/assets/85c8c22f-868d-42b7-9e5d-cb3d42f58801)

**Comment by psy501** [comment] 2024-12-08 18:58
![Capture d'écran 2024-12-08 200150](https://github.com/user-attachments/assets/cc605839-94dc-41c0-be7e-9d0c63e7282c)

**Comment by FdeAlexa** [comment] 2024-12-08 19:40
hi,
please try to edit the file inserting "a { channels 2 pcm "plughw:0,0" }" instead of the existing.
Best regards,
Francesco

**Comment by psy501** [comment] 2024-12-08 19:49
I have same error but this the alsa parameter change
![Capture d'écran 2024-12-08 205220](https://github.com/user-attachments/assets/7a5048d6-4bae-4750-bb6a-57d7f474b981)

**Comment by psy501** [comment] 2024-12-08 19:55
same error, after restart i have this in alsa settings
![Capture d'écran 2024-12-08 205220](https://github.com/user-attachments/assets/05590624-0f6b-479b-aba4-d2ee9f1a3e15)

**Comment by FdeAlexa** [comment] 2024-12-08 19:59
That should mean to insert "plughw:1,0" instead of "plughw:0,0"

**Comment by psy501** [comment] 2024-12-08 20:04
i have test but after restart i have alsaequal in _sndloop.conf.

**Comment by FdeAlexa** [comment] 2024-12-08 20:39
Is your DAC on USB?
in the config audio push scan and click on your DAC. It should be the first of the list (device = 0).

**Comment by FdeAlexa** [comment] 2024-12-08 20:48
sorry, you already sent the aplay -l your device should be "2" so in the config you should have:
a { channels 2 pcm "plughw:2,0" }
#b { channels 2 pcm "hw:Loopback,0" }
b { channels 2 pcm "pippopeppy" }        # Loopback via peppy output

**Comment by psy501** [comment] 2024-12-09 14:03
Thanks 

That was the problem, I have the 2 bars that move when I use: /home/alexis/peppyalsa/src/peppyalsa-client /var/tmp/peppyfifo

But there are no bars and needles that move with it:

cd /home/alexis/PeppyMeter
DISPLAY=:0 python peppymeter.py

I've got the various screens right, but is there any particular configuration to be made to the PeppyMeter/config.txt file?

**Comment by FdeAlexa** [comment] 2024-12-09 22:47
would you please send the content of the config.txt ?
Regards,
Francesco

**Comment by psy501** [comment] 2024-12-10 03:24
[current]
meter = random
random.meter.interval = 20
base.folder =
meter.folder = 1480x320
screen.width = 
screen.height = 
exit.on.touch = False
stop.display.on.touch = False
output.display = True
output.serial = False
output.i2c = False
output.pwm = False
output.http = False
use.logging = False
use.cache = True
cache.size = 20
frame.rate = 30

[sdl.env]
framebuffer.device = /dev/fb1
mouse.device = /dev/input/touchscreen
mouse.driver = TSLIB
mouse.enabled = True
video.driver = dummy
video.display = :0
double.buffer = False
no.frame = False

[serial.interface]
device.name = /dev/serial0
baud.rate = 9600
include.time = False
update.period = 0.1

[i2c.interface]
port = 1
left.channel.address = 0x21
right.channel.address = 0x20
output.size = 10
update.period = 0.1

[pwm.interface]
frequency = 500
gpio.pin.left = 24
gpio.pin.right = 25
update.period = 0.1

[http.interface]
target.url = http://localhost:8000/vumeter
update.period = 0.033

[web.server]
http.port = 8001

[data.source]
type = pipe
polling.interval = 0.04
pipe.name = /home/alexis/myfifo
volume.constant = 80.0
volume.min = 0.0
volume.max = 100.0
volume.max.in.pipe = 100.0
step = 6
mono.algorithm = average
http://localhost:8000/vumeter
stereo.algorithm = new
smooth.buffer.size = 4

**Comment by psy501** [comment] 2024-12-10 03:50
I noticed a difference in naming at the image folder level, on the 480*320 folders,... there is a separation with - on my 1480*320 folder the separation is _ . Could this be the cause?![Screenshot_20241210-043238.png](https://github.com/user-attachments/assets/f0154049-13e6-4428-a491-6e7eab24dd37)

![Screenshot_20241210-043232.png](https://github.com/user-attachments/assets/259785f3-58d4-4980-8dad-3c071948cb56)

**Comment by FdeAlexa** [comment] 2024-12-10 10:16
Hello psy501,
probably the problem is on the FIFO file: in the config.txt shold be:
pipe.name = /var/tmp/peppyfifo
Best regards,
Francesco

**Comment by psy501** [comment] 2024-12-10 14:17
Good job, thanks to you. it works now 😍

https://github.com/user-attachments/assets/1bdbe6d9-cdc5-42f2-b78b-69a9390ddf90

**Comment by FdeAlexa** [comment] 2024-12-10 20:13
I am happy that you are glad about it.
I think that we can close the issue.
Best regards,
Francesco

**Comment by psy501** [comment] 2024-12-16 19:24
Hi, I still have a little problem with moodeaudio. I would like to post my problem on the moode forum but I have already been waiting for several days for the admirer to validate my account.

My problem is when I start my raspberry I no longer have the moode interface displayed on the screen, yet the system is launched, accessible from the web, the sound works perfectly. Do you have an idea? 

Thank you
Alexis ![2024-12-16-20-03-35-886.jpg](https://github.com/user-attachments/assets/21b28119-e18a-48d3-8f5c-1959429a458f)

**Comment by psy501** [comment] 2024-12-16 19:34
peppy meter shows up when I play music, but it's on the side upside down![2024-12-16-20-33-59-515.jpg](https://github.com/user-attachments/assets/bf4befd9-8470-444e-bf47-6d90a406005d)

**Comment by FdeAlexa** [comment] 2024-12-16 20:50
What does it happen after your video dated december 10th?

**Comment by psy501** [comment] 2024-12-16 21:02
exactly nothing, finally I already had a little the problem when I restart the raspberry. the config.txt file often reset itself to the original. I just redid a complete installation, I had this bug after installing peppymeter maybe when I activated the autostart finally I'm not sure

**Comment by FdeAlexa** [comment] 2024-12-16 23:02
Hi,
I think you should tackle the problem gradually:
1. Please start by making raspberry, display and moode work correctly, including the music listening part. Is the config.txt file you are referring to the system one (/boot/config.txt)?
2. After that, turn off the system and check that, after turning it back on, everything works. At this point, save the situation (file and SD) so you can start again from a specific point.
3. At this point, start with PeppyAlsa and PeppyMeter, to get to the point of your video of December 10. Again Off, On, test and save file and SD.
4. Finally, you will be able to configure AutoPeppy, test everything and definitively save the situation (file and SD).
Let me know how things go.
As for the moOde Forum, I suggest you write an email to tim@moodeaudio.org.
Best regards,
Francesco

**Closed as completed** 2024-12-26 21:13 UTC

**Comment by psy501** [comment] 2024-12-26 21:16
Thanks, I completely reinstalled moode with all the addons and plugins. It works perfectly.... but suddenly I don't know why it blocks, but the most important thing is that it works. Is there a possibility to activate or deactivate the peppymeter after configuring the autostart? from the interface?

**Comment by FdeAlexa** [comment] 2024-12-26 21:40
Not from the interface. You can stop and start the service ( sudo service fda_autopeppy stop - sudo service fda_autopeppy start ).
Regards,
Francesco

**Comment by psy501** [comment] 2024-12-26 22:01
Ok 👍

**Comment by psy501** [comment] 2024-12-27 13:21
Sorry to bother you, but after 1 reboot it doesn't work again. moodeaudio starts up but remains stuck on my screen. The problem comes from autopeppy.service. 

sudo systemctl enable fda_autopeppy.service
sudo systemctl start fda_autopeppy.service

If i do :
sudo systemctl disable fda_autopeppy.service
sudo systemctl stop fda_autopeppy.service
Moodeaudio start perfectly

Peppymeter work great with:

cd /home/pi/PeppyMeter
DISPLAY=:0 python peppymeter.py

**Comment by FdeAlexa** [comment] 2024-12-27 21:58
Hi,
I have rebuild a system with it from scratch and it seems working perfectly after reboot and after shutdown too.
Some questions:
1. what model of raspberry are you using?
2. when it stucks would you please report the status of the service ( sudo service fda_autopeppy status )
3. what is your PeppyMeter config.txt ( cat /home/pi/PeppyMeter/config.txt )
Regards,
Francesco

**Comment by psy501** [comment] 2024-12-28 12:30
My raspberry is a pi 4 with 4go of ram. Here's the screenshot when I activate 'enable fda_autopeppy.service' the peppy meter works perfectly. But when I reboot the raspberry, it never displays the moode screen, but moode works with my pc via web. When I start it up, the peppy meter appears on the side, but only a bit. Then nothing else moode and peppymeter don't show up. 


![Capture d'écran 2024-12-28 131519](https://github.com/user-attachments/assets/a4bf2309-e4bc-40b8-832d-10ad4648ff27)
[config.txt](https://github.com/user-attachments/files/18266145/config.txt)

Thanks 
Alexis

**Comment by psy501** [comment] 2024-12-28 12:33
My config.txt in firmware

[config(1).txt](https://github.com/user-attachments/files/18266160/config.1.txt)

**Comment by psy501** [comment] 2024-12-28 12:42
Same as this at startup

![Capture d'écran 2024-12-28 133712](https://github.com/user-attachments/assets/3fe896f8-965e-48cd-8de3-febc3e70b942)
![Capture d'écran 2024-12-28 133718](https://github.com/user-attachments/assets/73066cd8-9f89-461e-92b6-2133efac3bd6)

**Comment by FdeAlexa** [comment] 2024-12-28 21:51
Hi Alexis,
I don't see any problems on your answers. As I said, today I have tested it (and I am still testing it) with several reboots and shutdowns and I never had a problem excluding one: when I rebooted the system without stop playing the music. Do you normally stop moOde before reboot?
Regards,
Francesco

**Comment by psy501** [comment] 2024-12-29 07:20
Yes I do a moodeaudio shutdown before turning off the power.  I really don't understand, why is peppymeter starting on the side of the screen at startup....? resolution problem? Xdg runtime dir problem ?

**Comment by psy501** [comment] 2024-12-29 07:30
I didn't do this, should I do it ?

![Screenshot_20241229-082900.png](https://github.com/user-attachments/assets/bff39e9c-5eee-4104-a875-4aecb81f7d9e)

**Comment by FdeAlexa** [comment] 2024-12-29 09:20
Alexis,
"Yes I do a moodeaudio shutdown before turning off the power" ....... Of course, but before: do you stop or pause the play? This is important too.

"I didn't do this, should I do it ?" ....... NO

Regards,
Francesco

**Comment by psy501** [comment] 2024-12-29 09:32
No, i not do this 👍

**Comment by FdeAlexa** [comment] 2024-12-29 13:57
this create a dirty status on the MPD and then the program I wrote, is affected by that. would you please try doing that and let me know.

**Comment by psy501** [comment] 2024-12-29 14:24
I just tried by pausing before restarting, that was indeed the problem. Bravo 👏👍 I would never have found it without you. Well I find it a bit restrictive, too bad 😌

Thanks 
Alexis

**Comment by psy501** [comment] 2024-12-29 14:26
I use homeassistant I will create a scene to turn off moodeaudio by pausing first 🤪

**Comment by FdeAlexa** [comment] 2024-12-29 16:57
well, please take a picture.
Regards,
Francesco
